import type { AdminAuditTargetTable } from "@/server/data/admin/audit-log";

// Frase legible por acción — si se agrega una acción nueva y no está acá,
// se muestra el código crudo como fallback (`ACTION_LABEL[action] ?? action`),
// nunca se rompe. Compartido entre `/admin/auditoria` y el historial por
// publicación en `/admin/publicaciones/[id]`.
export const ACTION_LABEL: Record<string, string> = {
  "listing.setFeatured": "Agregó/extendió destacado",
  "listing.removeFeaturedEarly": "Quitó destacado antes de tiempo",
  "listing.update": "Editó datos de la publicación",
  "listing.deleteImage": "Eliminó una foto de la publicación",
  "listing.reorderImages": "Reordenó las fotos de la publicación",
  "listing.setStatus": "Cambió el estado de la publicación",
  "listing.pause": "Pausó la publicación",
  "listing.softDelete": "Dio de baja la publicación",
  "listing.suspend": "Suspendió la publicación",
  "listing.unsuspend": "Reactivó la publicación suspendida",
  "listing.restore": "Restauró la publicación",
  "verification.approve": "Aprobó la verificación de identidad",
  "verification.addNote": "Agregó una observación de identidad",
  "subscription.grant": "Otorgó/renovó una suscripción",
  "subscription.cancel": "Canceló la suscripción",
  "subscription.adjustPurchasedPublications": "Ajustó publicaciones compradas",
  "subscription.adjustFeaturedVouchers": "Ajustó vouchers de destacado",
  "plan.toggleActive": "Dio de baja / reactivó un plan",
  "plan.update": "Editó un plan",
  "payment.approveCash": "Aprobó un pago en efectivo",
  "user.ban": "Baneó la cuenta",
  "user.unban": "Desbaneó la cuenta",
  "user.softDelete": "Eliminó la cuenta (lógico)",
  "user.restore": "Restauró la cuenta",
  "user.unlockLogin": "Desbloqueó el inicio de sesión",
  "user.suspend": "Suspendió la cuenta",
  "user.unsuspend": "Reactivó la cuenta suspendida",
  "user.setAdminRole": "Cambió el rol de administrador",
  "vehicleType.create": "Creó un tipo de vehículo",
  "vehicleType.update": "Editó un tipo de vehículo",
  "vehicleType.toggleActive": "Dio de baja / reactivó un tipo de vehículo",
  "brand.create": "Creó una marca",
  "brand.update": "Editó una marca",
  "brand.toggleActive": "Dio de baja / reactivó una marca",
  "model.create": "Creó un modelo",
  "model.update": "Editó un modelo",
  "model.toggleActive": "Dio de baja / reactivó un modelo",
  "version.create": "Creó una versión",
  "version.update": "Editó una versión",
  "version.toggleActive": "Dio de baja / reactivó una versión",
  "province.seed": "Importó las provincias del listado fijo",
  "province.create": "Creó una provincia",
  "province.update": "Editó una provincia",
  "province.toggleActive": "Dio de baja / reactivó una provincia",
  "locality.create": "Creó una localidad",
  "locality.bulkCreate": "Importó localidades en lote",
  "locality.update": "Editó una localidad",
  "locality.toggleActive": "Dio de baja / reactivó una localidad",
};

export const TARGET_TABLE_LABEL: Record<AdminAuditTargetTable, string> = {
  User: "Usuario",
  Listing: "Publicación",
  Payment: "Pago",
  Plan: "Plan",
  VerificationRequest: "Verificación de identidad",
  VehicleTypeCatalog: "Tipo de vehículo",
  Brand: "Marca",
  Model: "Modelo",
  Version: "Versión",
  Province: "Provincia",
  Locality: "Localidad",
};

export const TARGET_TABLES: AdminAuditTargetTable[] = [
  "User",
  "Listing",
  "Payment",
  "Plan",
  "VerificationRequest",
  "VehicleTypeCatalog",
  "Brand",
  "Model",
  "Version",
  "Province",
  "Locality",
];
